/** One self-contained page; dynamic values enter the DOM as text only. */
export function setupPage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cicero setup</title><style>
:root{color-scheme:light dark;font:16px/1.5 system-ui,sans-serif;--bg:#f5f6f8;--panel:#fff;--text:#15202b;--muted:#53616e;--accent:#16658a;--line:#d7dde2}
@media(prefers-color-scheme:dark){:root{--bg:#101820;--panel:#1c2731;--text:#e8f0f5;--muted:#acbac5;--accent:#68c9ee;--line:#364752}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}header{padding:1rem 1.5rem;border-bottom:1px solid var(--line);background:var(--panel)}h1{font-size:1.25rem;margin:0}main{display:grid;grid-template-columns:minmax(220px,270px) minmax(0,1fr);max-width:1100px;margin:auto;min-height:calc(100vh - 70px)}nav{padding:1.2rem;border-right:1px solid var(--line)}nav button{display:block;width:100%;text-align:left;margin:.25rem 0;padding:.5rem .65rem;background:none;border:1px solid transparent;border-radius:.5rem;color:var(--text);cursor:pointer}nav button[aria-current=true]{background:var(--panel);border-color:var(--accent);font-weight:700}.pipeline{font-size:.8rem;display:flex;flex-wrap:wrap;gap:.2rem;margin:0 0 1rem}.pipeline span{padding:.15rem .25rem;border-radius:.3rem;color:var(--muted)}.pipeline .active{background:var(--accent);color:var(--panel)}article{padding:1.5rem;max-width:760px}h2{margin-top:0}.card{background:var(--panel);border:1px solid var(--line);border-radius:.7rem;padding:1rem;margin:1rem 0}.label{font-weight:700;margin:.7rem 0 .1rem}.muted{color:var(--muted)}button.action{background:var(--accent);color:white;border:0;border-radius:.45rem;padding:.65rem .9rem;cursor:pointer;margin:.3rem .4rem .3rem 0}button.action:disabled{opacity:.5;cursor:not-allowed}select{padding:.4rem;font:inherit}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--bg);padding:1rem;border-radius:.5rem}.check{border-left:4px solid var(--line);padding:.3rem .7rem;margin:.4rem 0}.check.fail{border-color:#cb4d4d}.check.warn{border-color:#bf8a25}.check.ok{border-color:#2a985c}a{color:var(--accent)}
@media(max-width:700px){main{display:block}nav{border-right:0;border-bottom:1px solid var(--line);padding:.7rem}#steps{display:flex;overflow-x:auto}nav button{white-space:nowrap;width:auto}article{padding:1rem}}
</style></head><body><header><h1>🎙 Cicero guided setup <small class="muted">preview</small></h1></header><main><nav><div class="pipeline" id="pipeline"></div><div id="steps"></div></nav><article id="content">Loading…</article></main>
<script>
const params=new URLSearchParams(location.search);const fresh=params.get('token');if(fresh){sessionStorage.setItem('cicero-setup-token',fresh)}
const token=sessionStorage.getItem('cicero-setup-token');let state;
const el=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x};
async function api(path,body){const method=body===undefined?'GET':'POST';const headers={'x-cicero-setup-token':token||''};if(method==='POST'){headers['x-cicero-setup-csrf']='1';headers['content-type']='application/json'}const response=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data}
function addButton(parent,label,fn,disabled=false){const b=el('button',label,'action');b.disabled=disabled;b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){alert(e.message)}finally{b.disabled=false}};parent.append(b);return b}
function render(){const steps=document.getElementById('steps');const pipe=document.getElementById('pipeline');const content=document.getElementById('content');steps.replaceChildren();pipe.replaceChildren();content.replaceChildren();const selected=state.steps.find(s=>s.id===state.current)||state.steps[0];for(const name of ['mic','stt','brain','tts','speaker']){const span=el('span',name==='mic'?'🎤 mic':name==='speaker'?'🔊 speaker':name.toUpperCase());if(selected.pipeline===name)span.className='active';pipe.append(span);if(name!=='speaker')pipe.append(el('span','→'))}for(const step of state.steps){const b=el('button',step.title+(step.available?'':' · later'));b.setAttribute('aria-current',String(step.id===selected.id));b.onclick=async()=>{state=await api('/api/step',{id:step.id});render()};steps.append(b)}content.append(el('h2',selected.title));const explain=el('div',undefined,'card');for(const [label,key] of [['What this is','what'],['Why this recommendation','why'],['What will happen','happens']]){explain.append(el('p',label,'label'),el('p',selected.explain[key]))}const link=el('a','Learn more');link.href='https://github.com/5uck1ess/cicero/blob/main/'+selected.explain.learnMore;link.target='_blank';link.rel='noopener noreferrer';explain.append(link);content.append(explain);const box=el('div',undefined,'card');content.append(box);
if(selected.id==='system'){const f=state.detected;box.append(el('p',f.platform+' '+f.arch+' ('+f.release+')'),el('p','RAM: '+fmt(f.ramFreeBytes)+' free / '+fmt(f.ramTotalBytes)+' total'),el('p','Checkout disk: '+fmt(f.disks.checkout.freeBytes)+' free'),el('p','HF cache disk: '+fmt(f.disks.huggingface.freeBytes)+' free'),el('p',f.gpu.status==='ok'?'GPU: '+f.gpu.name+' — '+f.gpu.freeMiB+' / '+f.gpu.totalMiB+' MiB VRAM free/total':'GPU: '+f.gpu.status),el('p',f.reason));if(f.gpuWarning)box.append(el('p',f.gpuWarning,'check warn'));const label=el('label','Starting tier: ');const select=el('select');for(const tier of ['local-mlx','local-cuda','local-cpu']){const option=el('option',tier);option.value=tier;select.append(option)}select.value=state.tier;label.append(select);box.append(label);addButton(box,'Use this tier',async()=>{state=await api('/api/choice',{id:'system',choice:select.value});render()})}
else if(!selected.available){box.append(el('p','Coming in a later release. This step contributes no settings.','muted'))}
else if(selected.id==='check'){addButton(box,'Run checks',async()=>{state=await api('/api/check',{});render()});if(state.checkGroups){for(const [key,title] of [['blocking','Config problems — resolve before writing'],['notReady','Not ready yet — finish these before starting Cicero'],['warnings','Warnings'],['ok','Ready']]){const group=state.checkGroups[key];if(!group.length)continue;box.append(el('h3',title));for(const check of group){const item=el('div',check.name+': '+check.detail+(check.hint?' — '+check.hint:''),'check '+check.level);box.append(item)}}}}
else if(selected.id==='write'){box.append(el('p','Review the exact YAML that will be written:'));box.append(el('pre',state.yaml));if(state.existing.status==='valid')box.append(el('p','A valid config.yaml already exists. Edit it or back it up manually.'));if(state.existing.status==='invalid'){box.append(el('p','Existing config error: '+state.existing.error));addButton(box,'Back up and start fresh',async()=>{state=await api('/api/backup',{});render()})}if(state.existing.status==='other-file-error')box.append(el('p','Another Cicero home file failed to load: '+state.existing.error+' Fix that file; setup will not back up config.yaml.'));if(state.existing.status==='unsafe')box.append(el('p',state.existing.error));let acknowledged=false;if(state.requiresNotReadyAcknowledgement){box.append(el('h3','Not ready yet — finish these before starting Cicero'));for(const check of state.checkGroups.notReady){box.append(el('div',check.name+': '+check.detail+(check.hint?' — '+check.hint:''),'check fail'))}const label=el('label');const checkbox=el('input');checkbox.type='checkbox';label.append(checkbox,document.createTextNode(' I understand these components are not ready yet and will finish them before starting Cicero.'));box.append(label);checkbox.onchange=()=>{acknowledged=checkbox.checked;writeButton.disabled=!state.canWrite||!acknowledged}}const writeButton=addButton(box,'Write config.yaml',async()=>{state=await api('/api/write',{acknowledgeNotReady:acknowledged});render()},!state.canWrite||state.requiresNotReadyAcknowledgement)}
else if(selected.id==='handoff'){if(!state.written){box.append(el('p','Write the config before hand-off.'));return}if(state.handoff.customHome){box.append(el('p','Config was written to '+state.handoff.sourceConfigPath+'.'));box.append(el('p','cicero start reads only '+state.handoff.defaultConfigPath+'.'));box.append(el('p','To use this trial config, copy it to the default home:'));box.append(el('pre',state.handoff.copyCommand));box.append(el('p','If a config already exists there, review or back it up before running the copy command.'))}box.append(el('p','Start Cicero with:'));box.append(el('pre',state.startCommand));box.append(el('p','Web voice: https://<this-box>:8090 (the daemon prints its actual URL).'));box.append(el('p','Run cicero pair to show the phone QR.'));addButton(box,'Finish setup',async()=>{state=await api('/api/handoff',{});render()}) ;if(state.finished)box.append(el('p','Setup complete. You can close this page.'))}
}
function fmt(n){return n==null?'unavailable':(n/1024**3).toFixed(1)+' GiB'}
api('/api/state').then(s=>{state=s;render()}).catch(e=>{document.getElementById('content').textContent=e.message});
</script></body></html>`;
}
