/** One self-contained page; dynamic values enter the DOM as text only. */
export function setupPage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cicero setup</title><style>
:root{color-scheme:light dark;font:16px/1.5 system-ui,sans-serif;--bg:#f5f6f8;--panel:#fff;--text:#15202b;--muted:#53616e;--accent:#16658a;--line:#d7dde2}
@media(prefers-color-scheme:dark){:root{--bg:#101820;--panel:#1c2731;--text:#e8f0f5;--muted:#acbac5;--accent:#68c9ee;--line:#364752}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}header{padding:1rem 1.5rem;border-bottom:1px solid var(--line);background:var(--panel)}h1{font-size:1.25rem;margin:0}main{display:grid;grid-template-columns:minmax(220px,270px) minmax(0,1fr);max-width:1100px;margin:auto;min-height:calc(100vh - 70px)}nav{padding:1.2rem;border-right:1px solid var(--line)}nav button{display:block;width:100%;text-align:left;margin:.25rem 0;padding:.5rem .65rem;background:none;border:1px solid transparent;border-radius:.5rem;color:var(--text);cursor:pointer}nav button[aria-current=true]{background:var(--panel);border-color:var(--accent);font-weight:700}.pipeline{font-size:.8rem;display:flex;flex-wrap:wrap;gap:.2rem;margin:0 0 1rem}.pipeline span{padding:.15rem .25rem;border-radius:.3rem;color:var(--muted)}.pipeline .active{background:var(--accent);color:var(--panel)}article{padding:1.5rem;max-width:760px}h2{margin-top:0}.card{background:var(--panel);border:1px solid var(--line);border-radius:.7rem;padding:1rem;margin:1rem 0}.label{font-weight:700;margin:.7rem 0 .1rem}.muted{color:var(--muted)}button.action{background:var(--accent);color:white;border:0;border-radius:.45rem;padding:.65rem .9rem;cursor:pointer;margin:.3rem .4rem .3rem 0}button.action:disabled{opacity:.5;cursor:not-allowed}select{padding:.4rem;font:inherit}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--bg);padding:1rem;border-radius:.5rem}.check{border-left:4px solid var(--line);padding:.3rem .7rem;margin:.4rem 0}.check.fail{border-color:#cb4d4d}.check.warn{border-color:#bf8a25}.check.ok{border-color:#2a985c}a{color:var(--accent)}
.option{display:block;border:1px solid var(--line);border-radius:.5rem;padding:.7rem;margin:.5rem 0;cursor:pointer}.option:has(input:checked){border-color:var(--accent);background:var(--bg)}input[type=text],input[type=password],input[type=url],input[type=number]{font:inherit;max-width:100%;padding:.4rem;width:100%;border:1px solid var(--line);border-radius:.3rem;background:var(--panel);color:var(--text)}
@media(max-width:700px){main{display:block}nav{border-right:0;border-bottom:1px solid var(--line);padding:.7rem}#steps{display:flex;overflow-x:auto}nav button{white-space:nowrap;width:auto}article{padding:1rem}}
</style></head><body><header><h1>🎙 Cicero guided setup <small class="muted">preview</small></h1></header><main><nav><div class="pipeline" id="pipeline"></div><div id="steps"></div></nav><article id="content">Loading…</article></main>
<script>
const params=new URLSearchParams(location.search);const fresh=params.get('token');if(fresh){sessionStorage.setItem('cicero-setup-token',fresh)}
const token=sessionStorage.getItem('cicero-setup-token');let state;
const el=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x};
async function api(path,body){const method=body===undefined?'GET':'POST';const headers={'x-cicero-setup-token':token||''};if(method==='POST'){headers['x-cicero-setup-csrf']='1';headers['content-type']='application/json'}const response=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data}
function addButton(parent,label,fn,disabled=false){const b=el('button',label,'action');b.disabled=disabled;b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){alert(e.message)}finally{b.disabled=false}};parent.append(b);return b}
const names={'llama-cpp':'llama.cpp','ollama':'Ollama','lm-studio':'LM Studio','mlx-lm':'MLX','openai-compatible':'Other OpenAI-compatible','claude-code':'Claude Code','faster-whisper':'faster-whisper','mlx-whisper':'mlx-whisper','audiocpp':'audio.cpp','pocket-tts':'Pocket TTS','mlx-audio':'MLX Audio','elevenlabs':'ElevenLabs','wyoming':'Wyoming','hermes':'Hermes','multica':'Multica (not live-tested)','paperclip':'Paperclip (not live-tested)','none':'None'};
const tradeoffs={'llama-cpp':'Local GGUF model; low latency when resident, uses RAM or VRAM.','ollama':'Local model library; easy pulls, may reload between turns.','lm-studio':'Local desktop server; choose a loaded model in LM Studio.','mlx-lm':'Apple Silicon local model; uses unified memory.','openai-compatible':'Your own local, LAN, or cloud endpoint; latency and privacy depend on its host.','claude-code':'Agentic CLI with file and tool access; requires sign-in.','codex':'Agentic CLI with file and tool access; requires sign-in.','gemini':'Agentic CLI with file and tool access; requires sign-in.','qwen':'Agentic CLI with file and tool access; requires sign-in.','acp':'Agentic stdio harness; supply its executable and arguments.','faster-whisper':'Local transcription on CPU or CUDA; larger models use more memory.','mlx-whisper':'Local transcription optimized for Apple Silicon.','audiocpp':'Advanced CUDA path for audio.cpp; provision manually.','wyoming':'Use an existing speech server over the network.','kokoro':'Local speech with preset voices; no voice cloning.','pocket-tts':'CPU-friendly local voice cloning; requires a reference voice.','mlx-audio':'Local Apple Silicon speech; uses unified memory.','elevenlabs':'Cloud speech and voice cloning; needs an API key and real voice ID.','hermes':'Live-tested task board CLI.','multica':'Optional task board; adapter has not been live-tested.','paperclip':'Optional task board; adapter has not been live-tested.','none':'Skip task board notifications.'};
const instructions={
  'llama-cpp':['Install llama.cpp from https://github.com/ggml-org/llama.cpp','Start llama-server on port 8080 with a GGUF model.'],
  ollama:['Install from https://ollama.com/download','Run ollama serve, then ollama pull <model>.'],
  'lm-studio':['Install from https://lmstudio.ai/','Load a model, then start the local server on port 1234.'],
  'mlx-lm':['Read the Apple Silicon MLX runtime at https://github.com/ml-explore/mlx-examples','Install the MLX recipe from requirements/README.md; the Install step will automate this later.'],
  'claude-code':['Install from https://docs.anthropic.com/en/docs/claude-code/setup','Run claude and sign in.'],
  codex:['Install from https://developers.openai.com/codex/cli/','Run codex login.'],
  gemini:['Install from https://github.com/google-gemini/gemini-cli','Run gemini and sign in.'],
  qwen:['Install from https://github.com/QwenLM/qwen-code','Run qwen and sign in.'],
  hermes:['Install and sign in using https://hermes-agent.nousresearch.com.'],
  multica:['Install and configure the Multica CLI; see docs/notifications.md.'],
  paperclip:['Install and configure paperclipai; see docs/notifications.md.'],
  audiocpp:['Advanced Linux/NVIDIA path: read scripts/provision-audiocpp.sh. Do not run it without reviewing it.'],
  'pocket-tts':['Install the pocket-tts recipe from requirements/README.md; see docs/voice-cloning.md.'],
  elevenlabs:['Create an API key, then run cicero voice add to set a real tts.voice ID before starting.'],
  wyoming:['Start your existing Wyoming server and enter its host and port.']
};
function guideFor(option){if(option==='ollama'&&state.system.platform==='win32')return ['On Windows, use the Ollama installer at https://ollama.com/download/windows','Open Ollama, then run ollama pull <model>.'];if(option==='ollama'&&state.system.platform==='darwin')return ['On macOS, use the Ollama installer at https://ollama.com/download/mac','Open Ollama, then run ollama pull <model>.'];if(option==='ollama')return ['On Linux, follow https://ollama.com/download/linux','Run ollama serve, then ollama pull <model>.'];if(option==='llama-cpp')return ['For '+state.system.platform+', follow the build or package instructions at https://github.com/ggml-org/llama.cpp','Start llama-server on port 8080 with your GGUF model.'];return instructions[option]||['Read requirements/README.md for this engine; the later Install step will install its recipe.']}
function inputField(parent,label,value,type='text'){const wrap=el('label');wrap.append(el('span',label,'label'));const input=el('input');input.type=type;input.value=value||'';wrap.append(input);parent.append(wrap);return input}
function renderPicker(box,selected){const f=state.detected||{};const id=selected.id;const options=id==='provider'?['llama-cpp','ollama','lm-studio',...(f.mlxAvailable?['mlx-lm']:[]),'openai-compatible',...(f.cloudPresets||[])]:id==='brain'?(f.options||[]):id==='board'?['hermes','multica','paperclip','none']:(f.options||[]);let picked=state.selectedChoices?.[id]||f.recommended||options[0];box.append(el('p',f.reason||'Choose the runtime you want to use.','muted'));const cards=el('div');box.append(cards);const detail=el('div');box.append(detail);function draw(){cards.replaceChildren();detail.replaceChildren();for(const option of options){const label=el('label',undefined,'option');const radio=el('input');radio.type='radio';radio.name='picker';radio.value=option;radio.checked=option===picked;radio.onchange=()=>{picked=option;draw()};label.append(radio,document.createTextNode(' '+(names[option]||option)));
  const runtime=f.runtimes?.[option], installed=f.installed?.[option], status=f.status?.[option];const facts=runtime?(runtime.running?' running'+(runtime.models.length?' · '+runtime.models.length+' models':''):' offline'):installed!==undefined?(' '+(typeof installed==='object'?(installed.found?'installed '+(installed.version||''):'missing'):(installed?'installed':'missing'))):status?(option==='wyoming'?(' server '+(status.running?'answering':'offline')):(' '+(status.installed?'venv present':'venv missing')+'; '+(status.running?'port answering':'port offline'))):'';label.append(el('small',facts,'muted'),el('span',tradeoffs[option]||'OpenAI-compatible cloud API; needs an account and may incur charges.','muted'));cards.append(label)}
 const runtime=f.runtimes?.[picked];if(runtime?.models?.length)detail.append(el('p','Reported models: '+runtime.models.join(', '),'muted'));
 const fields={};if(picked==='llama-cpp')fields.model=inputField(detail,'GGUF path or HF repo ID',f.defaultModel);
 if(picked==='ollama'||picked==='lm-studio'){const select=el('select');for(const m of runtime?.models||[]){const item=el('option',m);item.value=m;select.append(item)}if(!select.options.length)detail.append(el('p','Start the runtime and Re-check to load its model list.','check warn'));else{const l=el('label','Model: ');l.append(select);detail.append(l)}fields.model=select}
 const remoteProvider=id==='provider'&&picked!=='llama-cpp'&&picked!=='ollama'&&picked!=='lm-studio'&&picked!=='mlx-lm';
 if(remoteProvider){if(picked==='openai-compatible')fields.baseUrl=inputField(detail,'HTTP(S) API base URL',state.providerModels?.id===picked?state.providerModels.baseUrl:'http://127.0.0.1:8000/v1','url');fields.apiKey=inputField(detail,'API key (optional)','', 'password');const l=el('label','Reported model: ');fields.model=el('select');for(const m of state.providerModels?.id===picked?state.providerModels.models:[]){const option=el('option',m);option.value=m;fields.model.append(option)}l.append(fields.model);detail.append(l);addButton(detail,'List models',async()=>{const listed=await api('/api/provider-models',{choice:{id:picked,baseUrl:fields.baseUrl?.value,apiKey:fields.apiKey.value}});fields.model.replaceChildren();for(const m of listed.models){const option=el('option',m);option.value=m;fields.model.append(option)}submit.disabled=!fields.model.options.length})}
 if(id==='brain'){if(picked==='acp')fields.command=inputField(detail,'Command as JSON argv, e.g. ["hermes","-p","voice","acp"]','["hermes","-p","voice","acp"]');if(picked==='openai-compatible'){fields.baseUrl=inputField(detail,'Brain API base URL','','url');fields.model=inputField(detail,'Model ID','');fields.apiKey=inputField(detail,'API key (optional)','','password')}else if(picked==='ollama'||(!['acp','claude-code','codex','gemini','qwen'].includes(picked))){fields.model=inputField(detail,'Model ID',picked==='ollama'?'qwen3.5:0.8b':'');if(picked!=='ollama')fields.apiKey=inputField(detail,'API key (optional)','','password')}if(picked==='claude-code'&&f.localTerminal){const l=el('label');const checkbox=el('input');checkbox.type='checkbox';fields.tab=checkbox;l.append(checkbox,document.createTextNode(' Use tab-inject in this local terminal'));detail.append(l)}}
 if(id==='board'&&picked==='paperclip'&&!f.paperclipEnv)fields.companyId=inputField(detail,'Paperclip company ID','');
 if((id==='stt'||id==='tts')&&picked==='wyoming'){fields.host=inputField(detail,'Wyoming host','127.0.0.1');fields.port=inputField(detail,'Port',id==='stt'?'10300':'10200','number')}if(picked==='elevenlabs')fields.apiKey=inputField(detail,'ElevenLabs API key','','password');
 if(fields.apiKey&&state.storedSecrets?.[id]&&state.selectedChoices?.[id]===picked)fields.apiKey.placeholder='Set — leave blank to keep';
 const installed=f.installed?.[picked];const missing=(runtime&&!runtime.running)||(typeof installed==='object'&&!installed.found)||(installed===false)||(f.status?.[picked]&&picked!=='wyoming'&&!f.status[picked].installed);if(missing||instructions[picked]){const guide=el('div',undefined,'card');guide.append(el('p','Guided setup','label'));for(const line of guideFor(picked)){guide.append(el('p',line));if(!line.startsWith('Install from')&&!line.startsWith('Install llama.cpp'))addButton(guide,'Copy',async()=>navigator.clipboard.writeText(line))}detail.append(guide)}
 if(f.probe)detail.append(el('p',f.probe.message,'check'));
 addButton(detail,'Re-check',async()=>{state=await api('/api/step',{id});render()});const submit=addButton(detail,'Use this choice',async()=>{const c={id:picked};for(const [key,field] of Object.entries(fields)){if(key==='tab'){if(field.checked)c.mode='tab-inject'}else if(key==='command'){c.command=JSON.parse(field.value)}else if(key==='port'){c.port=Number(field.value)}else c[key]=field.value}state=await api('/api/choice',{id,choice:c});render()},(remoteProvider||picked==='ollama'||picked==='lm-studio')&&!fields.model.options.length);}
 draw()}
function render(){const steps=document.getElementById('steps');const pipe=document.getElementById('pipeline');const content=document.getElementById('content');steps.replaceChildren();pipe.replaceChildren();content.replaceChildren();const selected=state.steps.find(s=>s.id===state.current)||state.steps[0];for(const name of ['mic','stt','brain','tts','speaker']){const span=el('span',name==='mic'?'🎤 mic':name==='speaker'?'🔊 speaker':name.toUpperCase());if(selected.pipeline===name)span.className='active';pipe.append(span);if(name!=='speaker')pipe.append(el('span','→'))}for(const step of state.steps){const b=el('button',step.title+(step.available?'':' · later'));b.setAttribute('aria-current',String(step.id===selected.id));b.onclick=async()=>{state=await api('/api/step',{id:step.id});render()};steps.append(b)}content.append(el('h2',selected.title));const explain=el('div',undefined,'card');for(const [label,key] of [['What this is','what'],['Why this recommendation','why'],['What will happen','happens']]){explain.append(el('p',label,'label'),el('p',selected.explain[key]))}const link=el('a','Learn more');link.href='https://github.com/5uck1ess/cicero/blob/main/'+selected.explain.learnMore;link.target='_blank';link.rel='noopener noreferrer';explain.append(link);content.append(explain);const box=el('div',undefined,'card');content.append(box);
if(selected.id==='system'){const f=state.detected;box.append(el('p',f.platform+' '+f.arch+' ('+f.release+')'),el('p','RAM: '+fmt(f.ramFreeBytes)+' free / '+fmt(f.ramTotalBytes)+' total'),el('p','Checkout disk: '+fmt(f.disks.checkout.freeBytes)+' free'),el('p','HF cache disk: '+fmt(f.disks.huggingface.freeBytes)+' free'),el('p',f.gpu.status==='ok'?'GPU: '+f.gpu.name+' — '+f.gpu.freeMiB+' / '+f.gpu.totalMiB+' MiB VRAM free/total':'GPU: '+f.gpu.status),el('p',f.reason));if(f.gpuWarning)box.append(el('p',f.gpuWarning,'check warn'));const label=el('label','Starting tier: ');const select=el('select');for(const tier of ['local-mlx','local-cuda','local-cpu']){const option=el('option',tier);option.value=tier;select.append(option)}select.value=state.tier;label.append(select);box.append(label);addButton(box,'Use this tier',async()=>{state=await api('/api/choice',{id:'system',choice:select.value});render()})}
else if(['provider','brain','board','stt','tts'].includes(selected.id)){renderPicker(box,selected)}
else if(!selected.available){box.append(el('p','Coming in a later release. This step contributes no settings.','muted'))}
else if(selected.id==='check'){addButton(box,'Run checks',async()=>{state=await api('/api/check',{});render()});if(state.checkGroups){for(const [key,title] of [['blocking','Config problems — resolve before writing'],['notReady','Not ready yet — finish these before starting Cicero'],['warnings','Warnings'],['ok','Ready']]){const group=state.checkGroups[key];if(!group.length)continue;box.append(el('h3',title));for(const check of group){const item=el('div',check.name+': '+check.detail+(check.hint?' — '+check.hint:''),'check '+check.level);box.append(item)}}}}
else if(selected.id==='write'){box.append(el('p','Review the annotated YAML preview. Private keys and the web token appear as “set”; their actual values will be written:'));box.append(el('pre',state.yaml));if(state.existing.status==='valid')box.append(el('p','A valid config.yaml already exists. Edit it or back it up manually.'));if(state.existing.status==='invalid'){box.append(el('p','Existing config error: '+state.existing.error));addButton(box,'Back up and start fresh',async()=>{state=await api('/api/backup',{});render()})}if(state.existing.status==='other-file-error')box.append(el('p','Another Cicero home file failed to load: '+state.existing.error+' Fix that file; setup will not back up config.yaml.'));if(state.existing.status==='unsafe')box.append(el('p',state.existing.error));let acknowledged=false;if(state.requiresNotReadyAcknowledgement){box.append(el('h3','Not ready yet — finish these before starting Cicero'));for(const check of state.checkGroups.notReady){box.append(el('div',check.name+': '+check.detail+(check.hint?' — '+check.hint:''),'check fail'))}const label=el('label');const checkbox=el('input');checkbox.type='checkbox';label.append(checkbox,document.createTextNode(' I understand these components are not ready yet and will finish them before starting Cicero.'));box.append(label);checkbox.onchange=()=>{acknowledged=checkbox.checked;writeButton.disabled=!state.canWrite||!acknowledged}}const writeButton=addButton(box,'Write config.yaml',async()=>{state=await api('/api/write',{acknowledgeNotReady:acknowledged});render()},!state.canWrite||state.requiresNotReadyAcknowledgement)}
else if(selected.id==='handoff'){if(!state.written){box.append(el('p','Write the config before hand-off.'));return}if(state.handoff.customHome){box.append(el('p','Config was written to '+state.handoff.sourceConfigPath+'.'));box.append(el('p','cicero start reads only '+state.handoff.defaultConfigPath+'.'));box.append(el('p','To use this trial config, copy it to the default home:'));box.append(el('pre',state.handoff.copyCommand));box.append(el('p','If a config already exists there, review or back it up before running the copy command.'))}box.append(el('p','Start Cicero with:'));box.append(el('pre',state.startCommand));box.append(el('p','Web voice: https://<this-box>:8090 (the daemon prints its actual URL).'));box.append(el('p','Run cicero pair to show the phone QR.'));addButton(box,'Finish setup',async()=>{state=await api('/api/handoff',{});render()}) ;if(state.finished)box.append(el('p','Setup complete. You can close this page.'))}
}
function fmt(n){return n==null?'unavailable':(n/1024**3).toFixed(1)+' GiB'}
api('/api/state').then(s=>{state=s;render()}).catch(e=>{document.getElementById('content').textContent=e.message});
</script></body></html>`;
}
