import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

interface ManifestCheck {
  file: string;
  python: string;
  expectedPins?: string[];
  onlyBinary?: string[];
}

const projectRoot = dirname(import.meta.dir);
const vibeVoiceCheck: ManifestCheck = {
  file: "vibevoice.txt",
  python: "3.11",
  expectedPins: [
    "torch==2.10.0",
    "vibevoice @ git+https://github.com/vibevoice-community/VibeVoice.git@07cb79feadd2d3fd7f47530d4c964a12857936a0",
    "vibevoice-api @ git+https://github.com/vibevoice-community/VibeVoice-API.git@72868f93056179bde83b0c6c3e5fb1d3af36ce0b",
  ],
  onlyBinary: ["torch"],
};

const sidecarChecks: ManifestCheck[] = [
  { file: "faster-whisper.txt", python: "3.10" },
  { file: "pocket-tts.txt", python: "3.11" },
  { file: "kokoro.txt", python: "3.11" },
  {
    file: "ser.txt",
    python: "3.11",
    expectedPins: ["torch==2.10.0", "torchaudio==2.10.0"],
    onlyBinary: ["torch", "torchaudio"],
  },
  {
    file: "telegram-call.txt",
    python: "3.11",
    expectedPins: ["tgcrypto==1.2.5"],
    onlyBinary: ["tgcrypto"],
  },
  { file: "turn.txt", python: "3.11" },
  vibeVoiceCheck,
];

const platformFlag = Bun.argv.indexOf("--platform");
const requestedPlatform = platformFlag >= 0 ? Bun.argv[platformFlag + 1] : undefined;
const platform = requestedPlatform ?? (
  process.platform === "win32" ? "windows" : process.platform === "darwin" ? "macos" : "linux"
);
const uvPlatforms: Record<string, string | undefined> = {
  linux: "x86_64-unknown-linux-gnu",
  windows: "x86_64-pc-windows-msvc",
  // Run natively on the macOS 14 arm64 CI runner: uv's generic Darwin target
  // intentionally assumes macOS 13 and cannot see current macOS 14+ MLX wheels.
  macos: undefined,
};

if (!(platform in uvPlatforms)) {
  throw new Error(`unsupported --platform '${platform}'; expected linux, windows, or macos`);
}
const uvPlatform = uvPlatforms[platform];
const checks = platform === "macos"
  ? [{ file: "mlx.txt", python: "3.12" }, vibeVoiceCheck]
  : sidecarChecks;

async function resolveManifest(check: ManifestCheck): Promise<string> {
  const manifest = join(projectRoot, "requirements", check.file);
  const output = join(tmpdir(), `cicero-${process.pid}-${platform}-${check.file}`);
  const command = [
    "uv",
    "pip",
    "compile",
    manifest,
    "--python-version",
    check.python,
    ...(uvPlatform ? ["--python-platform", uvPlatform] : []),
    ...(check.onlyBinary ?? []).flatMap((name) => ["--only-binary", name]),
    "--output-file",
    output,
    ...(platform === "macos" ? ["--prerelease=allow"] : []),
    "--quiet",
  ];

  try {
    const proc = Bun.spawn(command, { cwd: projectRoot, stdout: "pipe", stderr: "pipe" });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ]);
    if (exitCode !== 0) {
      throw new Error(`${command.join(" ")} exited ${exitCode}\n${stderr || stdout}`);
    }
    const compiled = await Bun.file(output).text();
    if (!compiled.includes("This file was autogenerated by uv")) {
      throw new Error(`uv produced an unexpected/empty lock for ${check.file}`);
    }
    for (const expected of check.expectedPins ?? []) {
      if (!compiled.split("\n").includes(expected)) {
        throw new Error(`${check.file} did not resolve the required pin ${expected}`);
      }
    }
    return `${check.file} (Python ${check.python})`;
  } catch (err: unknown) {
    throw new Error(`failed to resolve ${check.file} for ${platform}`, { cause: err });
  } finally {
    await rm(output, { force: true }).catch((err: unknown) => {
      console.error(`warning: could not remove ${output}: ${err instanceof Error ? err.message : String(err)}`);
    });
  }
}

try {
  const resolved = await Promise.all(checks.map(resolveManifest));
  console.log(`Resolved ${resolved.length} Python manifests for ${platform}: ${resolved.join(", ")}`);
} catch (err: unknown) {
  console.error(err instanceof Error ? err.message : String(err));
  if (err instanceof Error && err.cause) console.error(err.cause);
  process.exitCode = 1;
}
